### PR TITLE
Clean

### PR DESCRIPTION
**Pull request by gloomy-ghost**

### CODE REVIEW

**Review by runningdemo — APPROVED** [review]
Thank you

**Comment by gloomy-ghost** [comment]
Would you mind to add a public license for this extension? I'm looking for some modifications so that it will work on Firefox as well.

**Comment by runningdemo** [comment]
Sure, that's nice.

**Comment by gloomy-ghost** [comment]
FYI: https://choosealicense.com/

**Comment by runningdemo** [comment]
Done with it.

**Pull request merged**
